steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/campaignos-harness:latest', '.']

  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/campaignos-harness:latest']

  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    args:
      - 'gcloud'
      - 'run'
      - 'deploy'
      - 'campaignos-harness'
      - '--image=gcr.io/$PROJECT_ID/campaignos-harness:latest'
      - '--region=us-central1'
      - '--platform=managed'
      - '--allow-unauthenticated'
      - '--port=8080'
      - '--memory=2Gi'
      - '--cpu=2'
      - '--timeout=300'
      - '--set-env-vars=GOOGLE_CLOUD_PROJECT=$PROJECT_ID,BRAND_ASSETS_MODE=gcs,GCS_BUCKET=dauntless-karma-497108-b0-campaignos,SEARCH_MODE=live,SEARCH_ENGINE_ID=campaignos-briefing-search,BQ_DATASET=briefing_agent,BQ_LOGGING_ENABLED=true,ENVIRONMENT=production,LOG_LEVEL=INFO,GEMINI_MODEL_REASONING=groq/llama-3.3-70b-versatile,PGVECTOR_HOST=/cloudsql/dauntless-karma-497108-b0:us-central1:campaignos-pgvector,PGVECTOR_PORT=5432,PGVECTOR_USER=campaignos,PGVECTOR_DB=marketing,PGVECTOR_PASSWORD=campaignos123,USE_GEMINI_EMBEDDINGS=false,GEMINI_EMBEDDING_MODEL=gemini-embedding-2,FRONTEND_ORIGIN=https://campaignos-frontend-958438970145.us-central1.run.app'
      - '--set-secrets=GROQ_API_KEY=GROQ_API_KEY:latest,GOOGLE_API_KEY=GOOGLE_EMBEDDING_KEY:latest'
      - '--add-cloudsql-instances=dauntless-karma-497108-b0:us-central1:campaignos-pgvector'

images:
  - 'gcr.io/$PROJECT_ID/campaignos-harness:latest'

options:
  machineType: 'E2_HIGHCPU_8'
  logging: CLOUD_LOGGING_ONLY
