"""
agent_standalone.py — Run a single creative agent in isolation, given just
a brand and one free-text creative-direction prompt (no upstream pipeline
context required).

Unlike the full pipeline (run_creative_pipeline_direct / briefing_pipeline),
these are lightweight, single Gemini-call generations meant for quickly
exploring what one agent would produce for a brand + a one-line idea —
NOT the same depth/consistency as the full multi-agent chain, since each
call has no visibility into what the other agents would have produced.
"""

from __future__ import annotations

import json
import os
import re
import uuid

import structlog
from google import genai

from app.config import get_settings
from app.brand_assets import get_asset_loader

logger   = structlog.get_logger()
settings = get_settings()

# Live landing-page previews generated by standalone Poly runs — separate
# namespace from main.py's real-campaign _landing_pages dict, since these
# are throwaway demo previews, not actual published campaign assets.
_standalone_pages: dict[str, str] = {}

# Copy fields behind each landing_page_id, so a later "publish to channel X"
# click (email, google ads) can reuse what Poly already generated instead of
# asking the frontend to resend everything.
_standalone_channel_data: dict[str, dict] = {}


def get_standalone_page(page_id: str) -> str | None:
    return _standalone_pages.get(page_id)


def publish_standalone_channel(page_id: str, channel: str, to_email: str = "") -> dict:
    """
    Act on what a standalone Poly run already generated — real actions, same
    underlying functions as the full pipeline's /publish route, just scoped
    to a standalone (non-campaign) run:
      "landing_page" -> confirm the already-generated preview URL
      "email"        -> actually send a branded email via SMTP
      "google_ads"   -> generate the same mocked Google Ads preview
    """
    data = _standalone_channel_data.get(page_id)
    if not data:
        raise ValueError("Run Poly first — no generated content found for this preview.")

    harness_base = os.getenv("HARNESS_URL", "http://localhost:8000").rstrip("/")
    brand    = data["brand"]
    headline = data.get("headline", "")
    body     = data.get("body", "")
    cta      = data.get("cta", "") or "Learn More"

    if channel == "landing_page":
        return {"status": "live", "url": f"/agents/landing/{page_id}",
                "public_url": f"{harness_base}/agents/landing/{page_id}"}

    if channel == "email":
        if not to_email:
            return {"status": "skipped", "reason": "Enter a recipient email first."}
        from app.publisher import send_campaign_email
        return send_campaign_email(
            to_email       = to_email,
            brand          = brand,
            hero_message   = headline,
            short_headline = headline,
            cta            = cta,
            landing_url    = f"{harness_base}/agents/landing/{page_id}",
            logo_url       = f"{harness_base}/brand-logo/{brand}",
            email_subject  = data.get("email_subject", "") or headline,
            body_copy      = body,
        )

    if channel == "google_ads":
        from app.publisher import publish_google_ads
        return publish_google_ads(
            campaign_id     = f"standalone-{page_id}",
            brand           = brand,
            short_headline  = headline,
            medium_headline = headline,
            cta             = cta,
            body            = body,
        )

    raise ValueError(f"Unknown or unsupported channel '{channel}' for standalone runs.")

_client = None


def _genai_client():
    global _client
    if _client is None:
        _client = genai.Client(vertexai=True, project=settings.gcp_project, location=settings.gcp_region)
    return _client


def _brand_guidelines(brand: str) -> str:
    text = get_asset_loader().load_guidelines(brand)
    return text[:6000] if text else "(no brand guidelines on file for this brand — use general best practice)"


def _extract_brand(text: str) -> str | None:
    """Find which known (uploaded) brand is referenced in the free text, preferring the longest match —
    e.g. "UBS Bank for UK market, festive: christmas" -> "UBS Bank", not a shorter coincidental match."""
    known = get_asset_loader().list_brands()
    text_lower = text.lower()
    matches = [b for b in known if b.lower() in text_lower]
    return max(matches, key=len) if matches else None


def _parse_json_loose(text: str) -> dict | None:
    """Pull a JSON object out of a model response that may have wrapping prose/markdown fences."""
    match = re.search(r"\{.*\}", text, re.DOTALL)
    if not match:
        return None
    try:
        return json.loads(match.group(0))
    except Exception:
        return None


def _generate(persona: str, brand: str, prompt: str, output_instructions: str) -> dict:
    guidelines   = _brand_guidelines(brand)
    full_prompt = (
        f"{persona}\n\n"
        f"BRAND GUIDELINES for {brand}:\n{guidelines}\n\n"
        f"CREATIVE DIRECTION from the user: \"{prompt}\"\n\n"
        f"{output_instructions}"
    )
    resp = _genai_client().models.generate_content(
        model=settings.gemini_model_reasoning, contents=full_prompt,
    )
    raw = (resp.text or "").strip()
    return _parse_json_loose(raw) or {"raw": raw}


def run_briefing(brand: str, prompt: str) -> dict:
    data = _generate(
        "You are Logos, the briefing agent for an AI marketing campaign system. "
        "You validate a campaign idea against brand guidelines and give a quick quality read.",
        brand, prompt,
        'Respond ONLY with JSON, no markdown fences: '
        '{"goal": "...", "product": "...", "fan_truth": "the human insight behind this, one sentence", '
        '"audience": "who this is for, one phrase", "market": "...", "season": "...", '
        '"score": <integer 0-100>, "verdict": "PASS or NEEDS WORK", '
        '"summary": "1-2 sentence rationale for the score"}',
    )
    return {"agent": "briefing", **data}


def run_strategy(brand: str, prompt: str) -> dict:
    data = _generate(
        "You are Helia, the creative strategist for an AI marketing campaign system. "
        "You turn a one-line creative direction into a campaign's Big Idea and strategic framework.",
        brand, prompt,
        'Respond ONLY with JSON, no markdown fences: '
        '{"hero_message": "the Big Idea, one punchy sentence", '
        '"strategic_framework": "2-3 sentences on the strategic approach", '
        '"messaging_pillars": ["pillar 1", "pillar 2", "pillar 3"]}',
    )
    return {"agent": "strategy", **data}


def run_copy(brand: str, prompt: str) -> dict:
    data = _generate(
        "You are Ideon, the copywriter for an AI marketing campaign system. "
        "You write campaign headlines and copy that sound like a human wrote them, not corporate marketing-speak.",
        brand, prompt,
        'Respond ONLY with JSON, no markdown fences: '
        '{"headline": "...", "subline": "...", "body": "1-2 sentences", "cta": "2-3 words"}',
    )
    return {"agent": "copy", **data}


def run_culture(brand: str, prompt: str) -> dict:
    data = _generate(
        "You are Aether, the cultural intelligence researcher for an AI marketing campaign system. "
        "You identify cultural trends, moments, and audience behaviours relevant to a campaign.",
        brand, prompt,
        'Respond ONLY with JSON, no markdown fences: '
        '{"summary": "3-4 sentences of cultural insight relevant to this market and moment", '
        '"recommendations": ["recommendation 1", "recommendation 2", "recommendation 3"]}',
    )
    return {"agent": "culture", **data}


def run_channel(brand: str, prompt: str) -> dict:
    data = _generate(
        "You are Poly, the channel adaptation agent for an AI marketing campaign system. "
        "You adapt a campaign idea into platform-specific content for different channels, "
        "including a real website landing page.",
        brand, prompt,
        'Respond ONLY with JSON, no markdown fences: '
        '{"instagram": "caption text", "tiktok": "caption text", '
        '"email_subject": "subject line", "ooh": "short outdoor billboard line", '
        '"landing_headline": "short punchy hero headline for a website landing page", '
        '"landing_body": "1-2 sentence supporting copy for the landing page hero section", '
        '"landing_cta": "2-3 word call-to-action button label"}',
    )

    landing_page_id = uuid.uuid4().hex[:12]
    html = ""
    try:
        from app.publisher import generate_brand_website
        html = generate_brand_website(
            brand        = brand,
            hero_message = data.get("landing_headline", "") or prompt,
            body_copy    = data.get("landing_body", ""),
            cta          = data.get("landing_cta", "") or "Learn More",
            campaign_id  = f"standalone-{landing_page_id}",
        )
        _standalone_pages[landing_page_id] = html
        _standalone_channel_data[landing_page_id] = {
            "brand":         brand,
            "headline":      data.get("landing_headline", "") or prompt,
            "body":          data.get("landing_body", ""),
            "cta":           data.get("landing_cta", "") or "Learn More",
            "email_subject": data.get("email_subject", ""),
        }
    except Exception as e:
        logger.warning("standalone_landing_page_failed", brand=brand, error=str(e))
        landing_page_id = ""

    # Drop the raw landing_* fields from the flat result — they're inputs to the
    # generated page, not separate things to display alongside it.
    result = {k: v for k, v in data.items() if not k.startswith("landing_")}
    if landing_page_id:
        result["landing_page_id"]   = landing_page_id
        result["landing_page_html"] = html  # for the "code typing in" reveal before showing the live preview
    return {"agent": "channel", **result}


def run_kv(brand: str, prompt: str) -> dict:
    """
    Standalone Morphis: one text call for a headline + visual scene, one image
    call for the actual key visual, then the same Pillow brand-overlay
    post-processing (_apply_brand_overlay) the full pipeline uses so the
    headline actually renders on the image instead of falling back to just
    the brand name.

    Skips the full pipeline's reference-banner vision analysis step (an extra
    Gemini call for marginal quality gain) and any upstream big-idea/copy
    context — same standalone tradeoff already accepted for the other agents.
    """
    data = _generate(
        "You are Morphis, the key visual designer for an AI marketing campaign system. "
        "You write a short campaign headline and describe a visual scene for an image generator.",
        brand, prompt,
        'Respond ONLY with JSON, no markdown fences: '
        '{"headline": "short punchy campaign headline, 4-8 words", '
        '"scene": "2-3 sentences describing the visual scene — setting, subject(s), mood, lighting. '
        'Do not mention any text, words, or logos that should appear in the image."}',
    )
    headline = data.get("headline", "") or prompt
    scene    = data.get("scene", "") or prompt

    image_b64 = ""
    try:
        from google.genai import types as gtypes
        from app.creative_pipeline import _part_for_uri

        loader = get_asset_loader()
        brand_spelled = " - ".join(brand.upper())
        if brand == "UBS Bank":
            no_text_rule = (
                "TYPOGRAPHY RULE: Absolutely NO text, logos, numbers, or words anywhere in the "
                "image. All copy is added in post-production.\n\n"
            )
        else:
            no_text_rule = (
                f"CRITICAL BRAND RULE: Brand name spelled exactly: {brand_spelled} — this is a "
                f"completely fictional brand, not a real-world product.\n"
                "TYPOGRAPHY RULE: No text anywhere in the image except brand packaging labels "
                "if products are shown. All headline copy is added in post-production.\n\n"
            )
        image_prompt = (
            f"{no_text_rule}{scene}\n\n"
            "Aspect ratio 16:9, photorealistic, premium advertising photography."
        )

        contents: list = []
        logos = loader.list_logos(brand)
        if logos and (part := _part_for_uri(logos[0])):
            contents.append(f"BRAND IDENTITY REFERENCE for {brand} — colour palette and style "
                             f"only, do not render this logo in the image.")
            contents.append(part)
        products = loader.list_products(brand)
        if products and (part := _part_for_uri(products[0])):
            contents.append(f"PRODUCT REFERENCE for {brand} — match shape and colours if products "
                             f"are shown in the scene.")
            contents.append(part)
        contents.append(image_prompt)

        resp = _genai_client().models.generate_content(
            model    = settings.gemini_model_image,
            contents = contents,
            config   = gtypes.GenerateContentConfig(
                response_modalities = ["IMAGE", "TEXT"],
                image_config        = gtypes.ImageConfig(aspect_ratio="16:9"),
            ),
        )
        raw_bytes = None
        for part in resp.candidates[0].content.parts:
            if getattr(part, "inline_data", None) is not None:
                raw_bytes = part.inline_data.data
                break

        if raw_bytes:
            from app.runner import _apply_brand_overlay
            overlaid = _apply_brand_overlay(raw_bytes, brand, headline, products[:1], "")
            import base64
            image_b64 = base64.b64encode(overlaid).decode("utf-8")
    except Exception as e:
        logger.warning("standalone_kv_failed", brand=brand, error=str(e))

    return {"agent": "kv", "brand": brand, "headline": headline, "image_b64": image_b64}


def _build_branded_start_frame(brand: str):
    """
    Build a real 16:9 starting frame with the brand's logo actually stamped on it
    (same white-pill, top-right treatment _apply_brand_overlay uses for KV images),
    for Veo's image-to-video mode. Returns a google.genai.types.Image, or None if
    there's no usable background asset or logo for this brand.
    """
    try:
        from io import BytesIO
        from PIL import Image as PILImage, ImageDraw
        from google.genai import types as gtypes
        from app.creative_pipeline import _load_bytes

        loader = get_asset_loader()
        logos  = loader.list_logos(brand)
        if not logos:
            return None
        logo_bytes = _load_bytes(logos[0])
        if not logo_bytes:
            return None

        # Background: prefer an actual campaign asset/banner, fall back to a product shot.
        bg_uris = loader.list_assets(brand) or loader.list_products(brand)
        if not bg_uris:
            return None
        bg_bytes = _load_bytes(bg_uris[0])
        if not bg_bytes:
            return None

        bg = PILImage.open(BytesIO(bg_bytes)).convert("RGB")
        target_w, target_h = 1280, 720
        src_ratio, dst_ratio = bg.width / bg.height, target_w / target_h
        if src_ratio > dst_ratio:  # source wider — crop sides
            new_w = int(bg.height * dst_ratio)
            x0 = (bg.width - new_w) // 2
            bg = bg.crop((x0, 0, x0 + new_w, bg.height))
        else:  # source taller — crop top/bottom
            new_h = int(bg.width / dst_ratio)
            y0 = (bg.height - new_h) // 2
            bg = bg.crop((0, y0, bg.width, y0 + new_h))
        bg = bg.resize((target_w, target_h), PILImage.LANCZOS).convert("RGBA")

        logo = PILImage.open(BytesIO(logo_bytes)).convert("RGBA")
        margin = 32
        max_lw, max_lh = int(target_w * 0.14), int(target_h * 0.16)
        sc = min(max_lw / max(1, logo.width), max_lh / max(1, logo.height), 1.0)
        lw, lh = max(32, int(logo.width * sc)), max(32, int(logo.height * sc))
        logo = logo.resize((lw, lh), PILImage.LANCZOS)

        pad = max(8, int(lw * 0.18))
        bg_w, bg_h = lw + pad * 2, lh + pad * 2
        pill = PILImage.new("RGBA", (bg_w, bg_h), (0, 0, 0, 0))
        ImageDraw.Draw(pill).rounded_rectangle(
            [0, 0, bg_w - 1, bg_h - 1], radius=max(6, pad // 2), fill=(255, 255, 255, 220),
        )
        lx, ly = target_w - lw - margin - pad, margin
        bg.alpha_composite(pill, (lx, ly))
        bg.alpha_composite(logo, (lx + pad, ly + pad))

        buf = BytesIO()
        bg.convert("RGB").save(buf, format="JPEG", quality=90)
        return gtypes.Image(image_bytes=buf.getvalue(), mime_type="image/jpeg")
    except Exception as e:
        logger.warning("standalone_reel_start_frame_failed", brand=brand, error=str(e))
        return None


def _build_branded_end_frame(brand: str):
    """
    Build a clean 16:9 logo end-card — centered logo on a plain dark backdrop, the
    classic "ad closes on the brand" card. Passed as Veo's last_frame, which the SDK
    docs say is only supported alongside an image-to-video start frame (we have one).
    Returns a google.genai.types.Image, or None if there's no logo for this brand.
    """
    try:
        from io import BytesIO
        from PIL import Image as PILImage
        from google.genai import types as gtypes
        from app.creative_pipeline import _load_bytes

        loader = get_asset_loader()
        logos  = loader.list_logos(brand)
        if not logos:
            return None
        # Prefer a whiteBG/plain variant — reads cleanly on a dark card.
        logo_uri = next((p for p in logos if "whitebg" in p.lower()), logos[0])
        logo_bytes = _load_bytes(logo_uri)
        if not logo_bytes:
            return None

        target_w, target_h = 1280, 720
        card = PILImage.new("RGBA", (target_w, target_h), (10, 10, 19, 255))  # var(--page-bg) dark

        logo = PILImage.open(BytesIO(logo_bytes)).convert("RGBA")
        max_lw, max_lh = int(target_w * 0.32), int(target_h * 0.32)
        sc = min(max_lw / max(1, logo.width), max_lh / max(1, logo.height), 1.0)
        lw, lh = max(32, int(logo.width * sc)), max(32, int(logo.height * sc))
        logo = logo.resize((lw, lh), PILImage.LANCZOS)
        card.alpha_composite(logo, ((target_w - lw) // 2, (target_h - lh) // 2))

        buf = BytesIO()
        card.convert("RGB").save(buf, format="JPEG", quality=90)
        return gtypes.Image(image_bytes=buf.getvalue(), mime_type="image/jpeg")
    except Exception as e:
        logger.warning("standalone_reel_end_frame_failed", brand=brand, error=str(e))
        return None


def run_reel(brand: str, prompt: str) -> dict:
    """
    Standalone Kinetik — now matches the full pipeline's approach exactly:
    1. One Gemini text call to extract campaign context (big_idea, product, season,
       audience, voiceover line) from the user's free-text prompt + brand guidelines.
    2. Brand-specific visual scene direction (same templates as generate_campaign_reel).
    3. A second Gemini call generates the rich 80-100 word cinematic video+audio prompt
       using the same template the full pipeline uses.
    4. Pure text-to-video Veo call — no experimental image= / last_frame parameters,
       which the full pipeline never uses and which kept causing silent empty results.
    """
    # ── Step 1: Extract rich campaign context from the user prompt ────────────
    ctx = _generate(
        "You are Kinetik, the campaign reel director for an AI marketing campaign system.",
        brand, prompt,
        'Respond ONLY with JSON, no markdown fences: '
        '{"big_idea": "one punchy campaign concept sentence", '
        '"product": "specific product/service name, or empty string for pure service brands like banks", '
        '"season": "seasonal or festive context, e.g. Christmas, Summer, or empty string", '
        '"audience": "target audience in 5-8 words", '
        '"voiceover": "warm confident voiceover line, max 12 words"}',
    )
    big_idea  = ctx.get("big_idea", "") or prompt
    product   = ctx.get("product", "")
    season    = ctx.get("season", "")
    audience  = ctx.get("audience", "general audience")
    voiceover = ctx.get("voiceover", "") or big_idea
    _prod     = product or f"{brand} product"

    # ── Step 2: Brand + festive-aware visual scene ───────────────────────────
    _szn = season.lower() if season else ""
    _is_christmas  = any(x in _szn for x in ["christmas", "xmas", "festive", "winter fest"])
    _is_new_year   = any(x in _szn for x in ["new year", "nye", "new year"])
    _is_diwali     = "diwali" in _szn
    _is_summer     = any(x in _szn for x in ["summer", "festival", "outdoor"])
    _is_halloween  = "halloween" in _szn
    _is_valentine  = any(x in _szn for x in ["valentine", "love", "romance"])
    _is_easter     = "easter" in _szn

    def _festive_suffix() -> str:
        """Return a visual atmosphere suffix matching the detected season."""
        if _is_christmas:
            return ("Warm Christmas atmosphere — twinkling fairy lights, soft snowfall, "
                    "festive bokeh in the background, golden and red seasonal colour palette.")
        if _is_new_year:
            return ("New Year celebration atmosphere — golden confetti, city lights at midnight, "
                    "fireworks bokeh in the background, joyful and optimistic mood.")
        if _is_diwali:
            return ("Diwali celebration atmosphere — warm golden diyas, vibrant colours, "
                    "glittering light bokeh, joyful festive mood.")
        if _is_summer:
            return ("Summer outdoor atmosphere — bright sunlight, warm golden hour light, "
                    "vibrant energy, open landscapes.")
        if _is_halloween:
            return ("Halloween atmosphere — moody amber and deep purple tones, "
                    "atmospheric mist, dramatic cinematic lighting.")
        if _is_valentine:
            return ("Valentine mood — soft warm lighting, rose and blush colour tones, "
                    "intimate and romantic atmosphere.")
        if _is_easter:
            return ("Spring Easter atmosphere — fresh pastel tones, natural daylight, "
                    "blooming flowers in the background, bright and optimistic.")
        return ""

    def _sunglow_scene(p: str) -> str:
        festive = f" {_festive_suffix()}" if _festive_suffix() else ""
        if any(x in p.lower() for x in ["serum", "oil", "scalp", "treat"]):
            return (f"Close-up slow-motion of a woman applying {p} drops onto her fingertips, "
                    f"then running them through her hair as golden light particles trail behind. "
                    f"The {p} bottle gleams in warm studio light in the foreground. "
                    f"Magenta-pink and sunshine yellow brand colours. Warm glowing bokeh.{festive}")
        elif any(x in p.lower() for x in ["conditioner", "mask", "repair"]):
            return (f"A woman applying {p} through her hair in a bright studio, smiling confidently "
                    f"as her hair transforms into glossy, flowing locks in slow motion. "
                    f"The {p} tube displayed on a clean white surface. Sunglow magenta-pink palette.{festive}")
        else:
            return (f"A beautiful woman doing a slow-motion hair flip after washing with {p}, "
                    f"her incredibly shiny hair cascading through golden light particles and warm bokeh. "
                    f"The {p} bottle visible in foreground catching the light. "
                    f"Magenta-pink and sunshine yellow brand colours, dramatic rim lighting.{festive}")

    def _rnorr_scene(p: str) -> str:
        festive = f" {_festive_suffix()}" if _festive_suffix() else ""
        if any(x in p.lower() for x in ["gravy", "sauce", "cook-in", "liquid"]):
            return (f"A home cook pouring rich golden {p} over a sizzling pan of vegetables, "
                    f"dramatic steam and golden sauce trails catching warm kitchen light. "
                    f"The {p} bottle/pack on the counter, deep green and yellow brand accents.{festive}")
        elif any(x in p.lower() for x in ["bouillon", "powder", "seasoning"]):
            return (f"A close-up of {p} being sprinkled into a bubbling pot, golden powder "
                    f"dissolving into rich broth with cinematic steam wisps rising. "
                    f"Rnorr {p} pack beside fresh herbs. Deep forest green and yellow palette.{festive}")
        else:
            return (f"A home cook dropping a {p} into a steaming pot, watching it dissolve "
                    f"into rich golden broth — steam rising dramatically in warm amber kitchen light. "
                    f"The {p} box/jar on the counter beside fresh vegetables. "
                    f"Deep forest green and sunshine yellow brand colours.{festive}")

    def _boozt_scene(p: str) -> str:
        festive = f" {_festive_suffix()}" if _festive_suffix() else ""
        if any(x in p.lower() for x in ["sport", "hydration", "zero", "sugar"]):
            return (f"An athlete refreshing with a cold can of {p} after a workout, "
                    f"condensation droplets rolling down the can in slow motion under cool blue studio light. "
                    f"The {p} can gleams in the foreground against a deep navy background. "
                    f"Deep midnight navy and electric cobalt blue brand colours.{festive}")
        else:
            return (f"A confident young professional opening a can of {p} in a modern urban setting, "
                    f"cobalt blue light reflecting off the condensation-covered can as they take a refreshing sip. "
                    f"The {p} can displayed prominently in foreground under dramatic studio lighting. "
                    f"Deep midnight navy and cobalt blue brand colours.{festive}")

    def _glenfiddich_scene(p: str) -> str:
        festive = f" {_festive_suffix()}" if _festive_suffix() else ""
        return (f"A sophisticated man in a dark green blazer stands in a moody bar interior, "
                f"picking up a glass of {p} as amber liquid catches warm candlelight. "
                f"A teal-and-chartreuse Glenfiddich AMF1 bottle gleams prominently in the foreground. "
                f"Slow cinematic dolly push-in, bokeh highlights, deep teal and chartreuse brand palette. "
                f"Premium Scotch whisky advertising quality — elegant, restrained, confident.{festive}")

    def _ubs_scene(_p: str) -> str:
        # Pure visual/lifestyle — no brand name, no financial/wealth terminology whatsoever.
        # Even "Swiss" or the brand name in a video prompt triggers Veo RAI code 15236754.
        if _is_christmas:
            return ("A couple walks hand-in-hand along a beautifully decorated city street at Christmas, "
                    "twinkling fairy lights glowing in shop windows, soft snowflakes drifting, "
                    "warm golden festive light, bright red scarf detail catching the glow. "
                    "Cinematic slow dolly, shallow depth of field, joyful and aspirational mood.")
        if _is_new_year:
            return ("People celebrate on a rooftop terrace overlooking a sparkling city skyline at midnight, "
                    "golden confetti falling, fireworks illuminating the night sky, joyful and optimistic. "
                    "Cinematic wide establishing shot, aspirational and celebratory atmosphere.")
        if _is_summer:
            return ("A confident person walks through a sun-drenched European city square, "
                    "warm golden afternoon light, vibrant summer energy, purposeful and at ease. "
                    "Cinematic dolly movement, shallow depth of field, clean and modern atmosphere.")
        festive = f" {_festive_suffix()}" if _festive_suffix() else ""
        return ("A couple walks confidently through a sunlit city street, smiling warmly, "
                "golden light falling across elegant architecture, breath visible in the cool air. "
                "Slow cinematic dolly movement, shallow depth of field, bright red scarf detail. "
                f"Clean, modern, aspirational, understated elegance.{festive}")

    _BRAND_SCENE_FN = {
        "Sunglow":     _sunglow_scene,
        "Rnorr":       _rnorr_scene,
        "Boozt":       _boozt_scene,
        "Glenfiddich": _glenfiddich_scene,
        "UBS Bank":    _ubs_scene,
    }
    festive_ctx = f" {_festive_suffix()}" if _festive_suffix() else ""
    brand_scene = (
        _BRAND_SCENE_FN[brand](_prod) if brand in _BRAND_SCENE_FN
        else f"A premium cinematic advertising scene for {brand}, photorealistic, elegant and aspirational.{festive_ctx}"
    )

    # ── Step 3: Generate the rich 80-100 word cinematic prompt (same as full pipeline) ──
    _voiceover_line = f'A warm confident voiceover says: "{voiceover}"' if voiceover \
        else "A warm confident voiceover narrates the campaign tagline."
    prompt_req = (
        f"Write a single cinematic video+audio generation prompt (80-100 words) "
        f"for a 6-second {brand} campaign reel with voiceover.\n\n"
        f"Brand: {brand}\n"
        f"Product: {product or '(service brand — no physical product)'}\n"
        f"Campaign Big Idea: {big_idea}\n"
        f"Season/Context: {season or 'evergreen'}\n"
        f"Audience: {audience}\n"
        f"Voiceover text: \"{voiceover}\"\n"
        f"Base visual direction: {brand_scene}\n\n"
        f"Rules:\n"
        f"- Photorealistic, premium advertising quality, dynamic motion, brand colours prominent\n"
        f"- AUDIO: upbeat brand-appropriate background music + {_voiceover_line}\n"
        f"- The voiceover should be delivered confidently and warmly over the music\n"
        f"- No text or typography visible in the image\n"
        f"- CRITICAL: Do NOT use any financial or wealth terms: no 'wealth', 'investment', "
        f"'high-net-worth', 'banking', 'financial', 'portfolio', 'returns', 'assets', 'affluent', "
        f"'prosperity'. Describe only pure visual/lifestyle/emotional content.\n"
        f"Output the prompt only — no labels, no markdown, no explanation."
    )
    try:
        resp = _genai_client().models.generate_content(
            model=settings.gemini_model_reasoning,
            contents=prompt_req,
        )
        raw = (resp.text or "").strip()
        import re as _re
        # Strip any markdown label Gemini might prepend (e.g. "**VIDEO:**", "**Prompt:**")
        raw = _re.sub(r"^\*{0,2}[A-Z][A-Z\s:]{1,20}\*{0,2}:?\s*", "", raw).strip()
        # Also strip financial/wealth terms that slip through — replace with neutral alternatives
        _financial_terms = [
            (r"\bhigh[\s-]net[\s-]worth\b", "discerning"),
            (r"\bwealth management\b", "lifestyle"),
            (r"\baffluent\b", "accomplished"),
            (r"\bprosperous\b", "fulfilled"),
            (r"\binvestment\b", "future"),
            (r"\bportfolio\b", "journey"),
            (r"\bbanking\b", "service"),
            (r"\bfinancial\b", "personal"),
        ]
        for pattern, replacement in _financial_terms:
            raw = _re.sub(pattern, replacement, raw, flags=_re.IGNORECASE)
        final_prompt = raw
        if not final_prompt:
            final_prompt = f"Cinematic 6-second lifestyle reel. {brand_scene} AUDIO: {_voiceover_line}. No text."
    except Exception as e:
        logger.warning("standalone_reel_prompt_gen_failed", error=str(e))
        final_prompt = f"Cinematic 6-second {brand} campaign reel. {brand_scene} AUDIO: {_voiceover_line}. Photorealistic, premium quality. No text."

    logger.info("standalone_reel_prompt_ready", prompt=final_prompt[:120])

    # ── Step 4: Pure text-to-video Veo call (same as full pipeline — no image params) ──
    video_b64 = ""
    try:
        import base64
        import time as _time
        from google.genai.types import GenerateVideosConfig

        veo_model = os.getenv("VEO_MODEL", "veo-3.1-generate-001")
        client    = _genai_client()
        page_id   = uuid.uuid4().hex[:12]
        out_uri   = f"gs://{settings.gcs_bucket}/outputs/standalone-{page_id}/reel.mp4"

        _neg_prompt = (
            "text, words, subtitles, financial charts, graphs, stock prices, "
            "news tickers, legal disclaimers, violence, explicit content"
        )

        # DO NOT pass image= as start frame — Veo treats it as the video's primary subject,
        # causing it to just zoom/pan on the logo image instead of generating the cinematic scene.
        # Instead: text-to-video for the scene, last_frame for the logo end-card.
        # Note: last_frame is documented as "only for image-to-video", but we try it standalone
        # first; if it causes empty results we fall back to pure text-to-video.
        end_image = _build_branded_end_frame(brand)

        def _veo_call(video_text: str, with_end: bool = True) -> object:
            page = uuid.uuid4().hex[:12]
            uri  = f"gs://{settings.gcs_bucket}/outputs/standalone-{page}/reel.mp4"
            return client.models.generate_videos(
                model  = veo_model,
                prompt = video_text,
                config = GenerateVideosConfig(
                    aspect_ratio="16:9", duration_seconds=6,
                    output_gcs_uri=uri, number_of_videos=1, generate_audio=True,
                    negative_prompt=_neg_prompt,
                    last_frame=end_image if (with_end and end_image) else None,
                ),
            )

        def _poll(operation) -> object:
            deadline = _time.time() + 480
            while not operation.done:
                if _time.time() > deadline:
                    raise TimeoutError("Veo generation timed out after 8 minutes")
                _time.sleep(20)
                operation = client.operations.get(operation)
            return operation

        def _has_video(op) -> bool:
            return bool(op.result and op.result.generated_videos)

        def _rai_reasons(op) -> list:
            return getattr(op.result, "rai_media_filtered_reasons", None) if op and op.result else None

        operation = _poll(_veo_call(final_prompt, with_end=True))

        # last_frame may not be supported standalone (SDK says "image-to-video only").
        # If it causes empty results, retry as pure text-to-video without it.
        if end_image and not _has_video(operation) and not _rai_reasons(operation):
            logger.warning("standalone_reel_last_frame_empty_retrying_text_only", model=veo_model)
            operation = _poll(_veo_call(final_prompt, with_end=False))

        # If prompt was RAI-blocked, retry with the minimal safe scene-only fallback
        _rai = _rai_reasons(operation)
        if _rai and not _has_video(operation):
            logger.warning("standalone_reel_rai_blocked_retrying", model=veo_model, reasons=_rai)
            _safe_prompt = (
                # Safe fallback: pure lifestyle scene, no brand name, no financial terms
                f"Cinematic 6-second lifestyle advertisement. {brand_scene} "
                f"Photorealistic, premium quality, smooth camera motion, warm and aspirational mood. "
                f"AUDIO: gentle upbeat music with a confident voiceover. No text visible."
            )
            operation = _poll(_veo_call(_safe_prompt, with_end=False))

        if operation.result and operation.result.generated_videos:
            video_gcs = operation.result.generated_videos[0].video.uri
            from google.cloud import storage as _gcs
            without = video_gcs[5:]
            bucket_name, _, blob_path = without.partition("/")
            video_bytes = _gcs.Client().bucket(bucket_name).blob(blob_path).download_as_bytes()
            video_b64 = base64.b64encode(video_bytes).decode("utf-8")
            logger.info("standalone_reel_succeeded", model=veo_model)
        else:
            _rai2 = getattr(operation.result, "rai_media_filtered_reasons", None) if operation and operation.result else None
            logger.warning("standalone_reel_empty", model=veo_model, rai=_rai2)
    except Exception as e:
        logger.warning("standalone_reel_failed", brand=brand, error=str(e))

    return {"agent": "reel", "brand": brand, "headline": voiceover, "video_b64": video_b64}


_RUNNERS = {
    "briefing": run_briefing,
    "strategy": run_strategy,
    "copy":     run_copy,
    "culture":  run_culture,
    "channel":  run_channel,
    "kv":       run_kv,
    "reel":     run_reel,
}


def run_agent_standalone(agent_key: str, text: str) -> dict:
    """text is the whole free-text prompt, e.g. "UBS Bank for UK market, festive: christmas" —
    the brand is detected from it automatically rather than passed separately."""
    runner = _RUNNERS.get(agent_key)
    if not runner:
        raise ValueError(f"No standalone runner for agent '{agent_key}'.")
    brand = _extract_brand(text)
    if not brand:
        raise ValueError(
            "Couldn't tell which brand this is for — mention an uploaded brand's name in your prompt "
            '(e.g. "UBS Bank for UK market, festive: christmas").'
        )
    logger.info("agent_standalone_run", agent=agent_key, brand=brand)
    return runner(brand, text)
