"""
agent_standalone.py — Run a single creative agent in isolation, given just
a brand and one free-text creative-direction prompt (no upstream pipeline
context required).

Unlike the full pipeline (run_creative_pipeline_direct / briefing_pipeline),
these are lightweight, single Gemini-call generations meant for quickly
exploring what one agent would produce for a brand + a one-line idea —
NOT the same depth/consistency as the full multi-agent chain, since each
call has no visibility into what the other agents would have produced.
"""

from __future__ import annotations

import json
import os
import re
import uuid

import structlog
from google import genai

from app.config import get_settings
from app.brand_assets import get_asset_loader

logger   = structlog.get_logger()
settings = get_settings()

# Live landing-page previews generated by standalone Poly runs — separate
# namespace from main.py's real-campaign _landing_pages dict, since these
# are throwaway demo previews, not actual published campaign assets.
_standalone_pages: dict[str, str] = {}

# Copy fields behind each landing_page_id, so a later "publish to channel X"
# click (email, google ads) can reuse what Poly already generated instead of
# asking the frontend to resend everything.
_standalone_channel_data: dict[str, dict] = {}


def get_standalone_page(page_id: str) -> str | None:
    return _standalone_pages.get(page_id)


def publish_standalone_channel(page_id: str, channel: str, to_email: str = "") -> dict:
    """
    Act on what a standalone Poly run already generated — real actions, same
    underlying functions as the full pipeline's /publish route, just scoped
    to a standalone (non-campaign) run:
      "landing_page" -> confirm the already-generated preview URL
      "email"        -> actually send a branded email via SMTP
      "google_ads"   -> generate the same mocked Google Ads preview
    """
    data = _standalone_channel_data.get(page_id)
    if not data:
        raise ValueError("Run Poly first — no generated content found for this preview.")

    harness_base = os.getenv("HARNESS_URL", "http://localhost:8000").rstrip("/")
    brand    = data["brand"]
    headline = data.get("headline", "")
    body     = data.get("body", "")
    cta      = data.get("cta", "") or "Learn More"

    if channel == "landing_page":
        return {"status": "live", "url": f"/agents/landing/{page_id}",
                "public_url": f"{harness_base}/agents/landing/{page_id}"}

    if channel == "email":
        if not to_email:
            return {"status": "skipped", "reason": "Enter a recipient email first."}
        from app.publisher import send_campaign_email
        return send_campaign_email(
            to_email       = to_email,
            brand          = brand,
            hero_message   = headline,
            short_headline = headline,
            cta            = cta,
            landing_url    = f"{harness_base}/agents/landing/{page_id}",
            logo_url       = f"{harness_base}/brand-logo/{brand}",
            email_subject  = data.get("email_subject", "") or headline,
            body_copy      = body,
        )

    if channel == "google_ads":
        from app.publisher import publish_google_ads
        return publish_google_ads(
            campaign_id     = f"standalone-{page_id}",
            brand           = brand,
            short_headline  = headline,
            medium_headline = headline,
            cta             = cta,
            body            = body,
        )

    raise ValueError(f"Unknown or unsupported channel '{channel}' for standalone runs.")

_client = None


def _genai_client():
    global _client
    if _client is None:
        _client = genai.Client(vertexai=True, project=settings.gcp_project, location=settings.gcp_region)
    return _client


def _brand_guidelines(brand: str) -> str:
    text = get_asset_loader().load_guidelines(brand)
    return text[:6000] if text else "(no brand guidelines on file for this brand — use general best practice)"


def _extract_brand(text: str) -> str | None:
    """Find which known (uploaded) brand is referenced in the free text, preferring the longest match —
    e.g. "UBS Bank for UK market, festive: christmas" -> "UBS Bank", not a shorter coincidental match."""
    known = get_asset_loader().list_brands()
    text_lower = text.lower()
    matches = [b for b in known if b.lower() in text_lower]
    return max(matches, key=len) if matches else None


def _parse_json_loose(text: str) -> dict | None:
    """Pull a JSON object out of a model response that may have wrapping prose/markdown fences."""
    match = re.search(r"\{.*\}", text, re.DOTALL)
    if not match:
        return None
    try:
        return json.loads(match.group(0))
    except Exception:
        return None


def _generate(persona: str, brand: str, prompt: str, output_instructions: str) -> dict:
    guidelines   = _brand_guidelines(brand)
    full_prompt = (
        f"{persona}\n\n"
        f"BRAND GUIDELINES for {brand}:\n{guidelines}\n\n"
        f"CREATIVE DIRECTION from the user: \"{prompt}\"\n\n"
        f"{output_instructions}"
    )
    resp = _genai_client().models.generate_content(
        model=settings.gemini_model_reasoning, contents=full_prompt,
    )
    raw = (resp.text or "").strip()
    return _parse_json_loose(raw) or {"raw": raw}


def run_briefing(brand: str, prompt: str) -> dict:
    data = _generate(
        "You are Logos, the briefing agent for an AI marketing campaign system. "
        "You validate a campaign idea against brand guidelines and give a quick quality read.",
        brand, prompt,
        'Respond ONLY with JSON, no markdown fences: '
        '{"goal": "...", "product": "...", "fan_truth": "the human insight behind this, one sentence", '
        '"audience": "who this is for, one phrase", "market": "...", "season": "...", '
        '"score": <integer 0-100>, "verdict": "PASS or NEEDS WORK", '
        '"summary": "1-2 sentence rationale for the score"}',
    )
    return {"agent": "briefing", **data}


def run_strategy(brand: str, prompt: str) -> dict:
    data = _generate(
        "You are Helia, the creative strategist for an AI marketing campaign system. "
        "You turn a one-line creative direction into a campaign's Big Idea and strategic framework.",
        brand, prompt,
        'Respond ONLY with JSON, no markdown fences: '
        '{"hero_message": "the Big Idea, one punchy sentence", '
        '"strategic_framework": "2-3 sentences on the strategic approach", '
        '"messaging_pillars": ["pillar 1", "pillar 2", "pillar 3"]}',
    )
    return {"agent": "strategy", **data}


def run_copy(brand: str, prompt: str) -> dict:
    data = _generate(
        "You are Ideon, the copywriter for an AI marketing campaign system. "
        "You write campaign headlines and copy that sound like a human wrote them, not corporate marketing-speak.",
        brand, prompt,
        'Respond ONLY with JSON, no markdown fences: '
        '{"headline": "...", "subline": "...", "body": "1-2 sentences", "cta": "2-3 words"}',
    )
    return {"agent": "copy", **data}


def run_culture(brand: str, prompt: str) -> dict:
    data = _generate(
        "You are Aether, the cultural intelligence researcher for an AI marketing campaign system. "
        "You identify cultural trends, moments, and audience behaviours relevant to a campaign.",
        brand, prompt,
        'Respond ONLY with JSON, no markdown fences: '
        '{"summary": "3-4 sentences of cultural insight relevant to this market and moment", '
        '"recommendations": ["recommendation 1", "recommendation 2", "recommendation 3"]}',
    )
    return {"agent": "culture", **data}


def run_channel(brand: str, prompt: str) -> dict:
    data = _generate(
        "You are Poly, the channel adaptation agent for an AI marketing campaign system. "
        "You adapt a campaign idea into platform-specific content for different channels, "
        "including a real website landing page.",
        brand, prompt,
        'Respond ONLY with JSON, no markdown fences: '
        '{"instagram": "caption text", "tiktok": "caption text", '
        '"email_subject": "subject line", "ooh": "short outdoor billboard line", '
        '"landing_headline": "short punchy hero headline for a website landing page", '
        '"landing_body": "1-2 sentence supporting copy for the landing page hero section", '
        '"landing_cta": "2-3 word call-to-action button label"}',
    )

    landing_page_id = uuid.uuid4().hex[:12]
    html = ""
    try:
        from app.publisher import generate_brand_website
        html = generate_brand_website(
            brand        = brand,
            hero_message = data.get("landing_headline", "") or prompt,
            body_copy    = data.get("landing_body", ""),
            cta          = data.get("landing_cta", "") or "Learn More",
            campaign_id  = f"standalone-{landing_page_id}",
        )
        _standalone_pages[landing_page_id] = html
        _standalone_channel_data[landing_page_id] = {
            "brand":         brand,
            "headline":      data.get("landing_headline", "") or prompt,
            "body":          data.get("landing_body", ""),
            "cta":           data.get("landing_cta", "") or "Learn More",
            "email_subject": data.get("email_subject", ""),
        }
    except Exception as e:
        logger.warning("standalone_landing_page_failed", brand=brand, error=str(e))
        landing_page_id = ""

    # Drop the raw landing_* fields from the flat result — they're inputs to the
    # generated page, not separate things to display alongside it.
    result = {k: v for k, v in data.items() if not k.startswith("landing_")}
    if landing_page_id:
        result["landing_page_id"]   = landing_page_id
        result["landing_page_html"] = html  # for the "code typing in" reveal before showing the live preview
    return {"agent": "channel", **result}


def run_kv(brand: str, prompt: str) -> dict:
    """
    Standalone Morphis: one text call for a headline + visual scene, one image
    call for the actual key visual, then the same Pillow brand-overlay
    post-processing (_apply_brand_overlay) the full pipeline uses so the
    headline actually renders on the image instead of falling back to just
    the brand name.

    Skips the full pipeline's reference-banner vision analysis step (an extra
    Gemini call for marginal quality gain) and any upstream big-idea/copy
    context — same standalone tradeoff already accepted for the other agents.
    """
    data = _generate(
        "You are Morphis, the key visual designer for an AI marketing campaign system. "
        "You write a short campaign headline and describe a visual scene for an image generator.",
        brand, prompt,
        'Respond ONLY with JSON, no markdown fences: '
        '{"headline": "short punchy campaign headline, 4-8 words", '
        '"scene": "2-3 sentences describing the visual scene — setting, subject(s), mood, lighting. '
        'Do not mention any text, words, or logos that should appear in the image."}',
    )
    headline = data.get("headline", "") or prompt
    scene    = data.get("scene", "") or prompt

    image_b64 = ""
    try:
        from google.genai import types as gtypes
        from app.creative_pipeline import _part_for_uri

        loader = get_asset_loader()
        brand_spelled = " - ".join(brand.upper())
        if brand == "UBS Bank":
            no_text_rule = (
                "TYPOGRAPHY RULE: Absolutely NO text, logos, numbers, or words anywhere in the "
                "image. All copy is added in post-production.\n\n"
            )
        else:
            no_text_rule = (
                f"CRITICAL BRAND RULE: Brand name spelled exactly: {brand_spelled} — this is a "
                f"completely fictional brand, not a real-world product.\n"
                "TYPOGRAPHY RULE: No text anywhere in the image except brand packaging labels "
                "if products are shown. All headline copy is added in post-production.\n\n"
            )
        image_prompt = (
            f"{no_text_rule}{scene}\n\n"
            "Aspect ratio 16:9, photorealistic, premium advertising photography."
        )

        contents: list = []
        logos = loader.list_logos(brand)
        # Prefer a logo that contains the brand name and isn't a pure-white variant
        _bslug = brand.split()[0].lower()
        _ref_logo = (
            next((p for p in logos if _bslug in p.lower() and "_dark" in p.lower()), None) or
            next((p for p in logos if _bslug in p.lower() and "_white" not in p.lower()), None) or
            next((p for p in logos if _bslug in p.lower()), None) or
            (logos[0] if logos else None)
        )
        if _ref_logo and (part := _part_for_uri(_ref_logo)):
            contents.append(f"BRAND IDENTITY REFERENCE for {brand} — colour palette and style "
                             f"only, do not render this logo in the image.")
            contents.append(part)
        products = loader.list_products(brand)
        if products and (part := _part_for_uri(products[0])):
            contents.append(f"PRODUCT REFERENCE for {brand} — match shape and colours if products "
                             f"are shown in the scene.")
            contents.append(part)
        contents.append(image_prompt)

        resp = _genai_client().models.generate_content(
            model    = settings.gemini_model_image,
            contents = contents,
            config   = gtypes.GenerateContentConfig(
                response_modalities = ["IMAGE", "TEXT"],
                image_config        = gtypes.ImageConfig(aspect_ratio="16:9"),
            ),
        )
        raw_bytes = None
        for part in resp.candidates[0].content.parts:
            if getattr(part, "inline_data", None) is not None:
                raw_bytes = part.inline_data.data
                break

        if raw_bytes:
            from app.runner import _apply_brand_overlay
            overlaid = _apply_brand_overlay(raw_bytes, brand, headline, products[:1], "")
            import base64
            image_b64 = base64.b64encode(overlaid).decode("utf-8")
    except Exception as e:
        logger.warning("standalone_kv_failed", brand=brand, error=str(e))

    return {"agent": "kv", "brand": brand, "headline": headline, "image_b64": image_b64}


def _build_branded_start_frame(brand: str):
    """
    Build a real 16:9 starting frame with the brand's logo actually stamped on it
    (same white-pill, top-right treatment _apply_brand_overlay uses for KV images),
    for Veo's image-to-video mode. Returns a google.genai.types.Image, or None if
    there's no usable background asset or logo for this brand.
    """
    try:
        from io import BytesIO
        from PIL import Image as PILImage, ImageDraw
        from google.genai import types as gtypes
        from app.creative_pipeline import _load_bytes

        loader = get_asset_loader()
        logos  = loader.list_logos(brand)
        if not logos:
            return None
        logo_bytes = _load_bytes(logos[0])
        if not logo_bytes:
            return None

        # Background: prefer an actual campaign asset/banner, fall back to a product shot.
        bg_uris = loader.list_assets(brand) or loader.list_products(brand)
        if not bg_uris:
            return None
        bg_bytes = _load_bytes(bg_uris[0])
        if not bg_bytes:
            return None

        bg = PILImage.open(BytesIO(bg_bytes)).convert("RGB")
        target_w, target_h = 1280, 720
        src_ratio, dst_ratio = bg.width / bg.height, target_w / target_h
        if src_ratio > dst_ratio:  # source wider — crop sides
            new_w = int(bg.height * dst_ratio)
            x0 = (bg.width - new_w) // 2
            bg = bg.crop((x0, 0, x0 + new_w, bg.height))
        else:  # source taller — crop top/bottom
            new_h = int(bg.width / dst_ratio)
            y0 = (bg.height - new_h) // 2
            bg = bg.crop((0, y0, bg.width, y0 + new_h))
        bg = bg.resize((target_w, target_h), PILImage.LANCZOS).convert("RGBA")

        logo = PILImage.open(BytesIO(logo_bytes)).convert("RGBA")
        margin = 32
        max_lw, max_lh = int(target_w * 0.14), int(target_h * 0.16)
        sc = min(max_lw / max(1, logo.width), max_lh / max(1, logo.height), 1.0)
        lw, lh = max(32, int(logo.width * sc)), max(32, int(logo.height * sc))
        logo = logo.resize((lw, lh), PILImage.LANCZOS)

        pad = max(8, int(lw * 0.18))
        bg_w, bg_h = lw + pad * 2, lh + pad * 2
        pill = PILImage.new("RGBA", (bg_w, bg_h), (0, 0, 0, 0))
        ImageDraw.Draw(pill).rounded_rectangle(
            [0, 0, bg_w - 1, bg_h - 1], radius=max(6, pad // 2), fill=(255, 255, 255, 220),
        )
        lx, ly = target_w - lw - margin - pad, margin
        bg.alpha_composite(pill, (lx, ly))
        bg.alpha_composite(logo, (lx + pad, ly + pad))

        buf = BytesIO()
        bg.convert("RGB").save(buf, format="JPEG", quality=90)
        return gtypes.Image(image_bytes=buf.getvalue(), mime_type="image/jpeg")
    except Exception as e:
        logger.warning("standalone_reel_start_frame_failed", brand=brand, error=str(e))
        return None


def _build_branded_end_frame(brand: str):
    """
    Build a clean 16:9 logo end-card — centered logo on a plain dark backdrop, the
    classic "ad closes on the brand" card. Passed as Veo's last_frame, which the SDK
    docs say is only supported alongside an image-to-video start frame (we have one).
    Returns a google.genai.types.Image, or None if there's no logo for this brand.
    """
    try:
        from io import BytesIO
        from PIL import Image as PILImage
        from google.genai import types as gtypes
        from app.creative_pipeline import _load_bytes

        loader = get_asset_loader()
        logos  = loader.list_logos(brand)
        if not logos:
            return None
        # Prefer a whiteBG/plain variant — reads cleanly on a dark card.
        logo_uri = next((p for p in logos if "whitebg" in p.lower()), logos[0])
        logo_bytes = _load_bytes(logo_uri)
        if not logo_bytes:
            return None

        target_w, target_h = 1280, 720
        card = PILImage.new("RGBA", (target_w, target_h), (10, 10, 19, 255))  # var(--page-bg) dark

        logo = PILImage.open(BytesIO(logo_bytes)).convert("RGBA")
        max_lw, max_lh = int(target_w * 0.32), int(target_h * 0.32)
        sc = min(max_lw / max(1, logo.width), max_lh / max(1, logo.height), 1.0)
        lw, lh = max(32, int(logo.width * sc)), max(32, int(logo.height * sc))
        logo = logo.resize((lw, lh), PILImage.LANCZOS)
        card.alpha_composite(logo, ((target_w - lw) // 2, (target_h - lh) // 2))

        buf = BytesIO()
        card.convert("RGB").save(buf, format="JPEG", quality=90)
        return gtypes.Image(image_bytes=buf.getvalue(), mime_type="image/jpeg")
    except Exception as e:
        logger.warning("standalone_reel_end_frame_failed", brand=brand, error=str(e))
        return None


def run_reel(brand: str, prompt: str) -> dict:
    """
    Standalone Kinetik — now matches the full pipeline's approach exactly:
    1. One Gemini text call to extract campaign context (big_idea, product, season,
       audience, voiceover line) from the user's free-text prompt + brand guidelines.
    2. Brand-specific visual scene direction (same templates as generate_campaign_reel).
    3. A second Gemini call generates the rich 80-100 word cinematic video+audio prompt
       using the same template the full pipeline uses.
    4. Pure text-to-video Veo call — no experimental image= / last_frame parameters,
       which the full pipeline never uses and which kept causing silent empty results.
    """
    # ── Step 1: Extract rich campaign context from the user prompt ────────────
    ctx = _generate(
        "You are Kinetik, the campaign reel director for an AI marketing campaign system.",
        brand, prompt,
        'Respond ONLY with JSON, no markdown fences: '
        '{"big_idea": "one punchy campaign concept sentence", '
        '"product": "specific product/service name, or empty string for pure service brands like banks", '
        '"season": "seasonal or festive context, e.g. Christmas, Summer, or empty string", '
        '"audience": "target audience in 5-8 words", '
        '"voiceover": "warm confident voiceover line, max 12 words"}',
    )
    big_idea  = ctx.get("big_idea", "") or prompt
    product   = ctx.get("product", "")
    season    = ctx.get("season", "")
    audience  = ctx.get("audience", "general audience")
    voiceover = ctx.get("voiceover", "") or big_idea
    _prod     = product or f"{brand} product"

    # ── Step 2: Brand + occasion-aware visual scene ──────────────────────────
    import random as _rnd
    _szn = season.lower() if season else ""
    _ol  = prompt.lower()

    _is_christmas  = any(x in _szn for x in ["christmas", "xmas", "festive", "advent"])
    _is_new_year   = any(x in _szn for x in ["new year", "nye"])
    _is_diwali     = any(x in _szn for x in ["diwali", "deepavali"])
    _is_valentine  = any(x in _szn for x in ["valentine", "valentines"])
    _is_easter     = "easter" in _szn
    _is_halloween  = "halloween" in _szn
    _is_summer     = any(x in _szn for x in ["summer"])
    _is_autumn     = any(x in _szn for x in ["autumn", "fall"])
    _is_winter     = "winter" in _szn and not _is_christmas
    _is_spring     = "spring" in _szn

    # Each brand has fully distinct scene descriptions per occasion.
    # random.choice() picks one of 2-3 variants so the same brief
    # never produces the same video twice.

    def _sunglow_scene(p: str) -> str:
        if _is_christmas:
            return _rnd.choice([
                f"Three diverse women (25-38) laughing and getting ready together for Christmas night, "
                f"doing each other's hair in front of a beautifully decorated Christmas tree covered in warm fairy lights. "
                f"Red and gold baubles everywhere, {p} products on the vanity, shiny hair catching the festive glow. "
                f"Magenta-pink and deep red colour palette, genuine sisterhood and festive joy.",
                f"A mother and teenage daughter doing their hair together on Christmas morning — "
                f"kitchen table covered in gift wrap, Christmas tree in background, fairy lights strung across the window. "
                f"The daughter's hair transforms in slow motion, {p} bottle centred on the table between them. "
                f"Warm golden Christmas kitchen light, red and gold palette, pure family warmth.",
            ])
        if _is_diwali:
            return _rnd.choice([
                f"Three South Asian women (20-45) in jewel-toned saris and salwars getting ready together for Diwali, "
                f"doing each other's hair surrounded by diyas and marigold garlands. "
                f"Warm golden diya light catches their hair mid-flip, {p} products gleaming on the dressing table. "
                f"Rich jewel-tone palette — deep magenta, gold and emerald — joyful and celebratory.",
                f"A South Asian grandmother, mother and daughter getting ready for Diwali puja — "
                f"three generations doing hair together, diyas flickering, rangoli visible on the floor behind them. "
                f"{p} bottle between them, hair FLYING in slow motion catching golden diya light. "
                f"Vibrant traditional outfits, warm amber and gold colour palette.",
            ])
        if _is_new_year:
            return _rnd.choice([
                f"Four women (22-35) getting glamorous together for New Year's Eve — sequined outfits, "
                f"champagne flutes on the vanity, golden confetti beginning to fall from the ceiling. "
                f"Hair FLYING in slow motion as they count down, {p} bottle centre-frame, golden and silver palette. "
                f"Pure NYE euphoria and sisterhood.",
                f"A woman doing a dramatic hair flip in a penthouse as fireworks explode outside the floor-to-ceiling windows "
                f"behind her — golden bursts of light catching every strand of her impossibly shiny hair. "
                f"{p} bottle on the window ledge, midnight skyline, Sunglow magenta-pink and gold palette.",
            ])
        if _is_valentine:
            return _rnd.choice([
                f"A woman styling her hair with {p} for a Valentine's date — roses and petals on the dressing table, "
                f"warm rose-gold candlelight catching her flowing locks. Slow-motion hair flip with soft pink bokeh "
                f"and red rose petals raining down. Intimate, romantic, Sunglow pink and rose-gold palette.",
                f"Two women (best friends) getting ready for Valentine's night out together — laughing, "
                f"doing each other's hair, {p} products and red roses on the vanity, pink champagne on the table. "
                f"Warm rose-toned lighting, pure joy and self-love energy.",
            ])
        if _is_easter:
            return (f"A woman doing a slow-motion hair flip outdoors in a spring garden full of blooming cherry blossoms — "
                    f"pastel pink petals drifting through her shiny flowing hair. {p} bottle in foreground catching sunlight. "
                    f"Fresh spring light, pastel pink and yellow palette, renewal and joy.")
        if _is_halloween:
            return (f"A woman with dramatically gorgeous styled hair at a Halloween party — "
                    f"deep purple and amber lighting, jack-o-lanterns glowing in the background, "
                    f"her hair catching the moody cinematic light beautifully. {p} bottle in foreground, "
                    f"deep magenta-purple palette, glamorous and slightly mysterious.")
        if _is_summer:
            return _rnd.choice([
                f"A woman doing a dramatic slow-motion hair flip on a sun-drenched beach, "
                f"golden hour light turning her shiny hair into a cascade of light. "
                f"Warm ocean in the background, {p} bottle half-buried in sand in the foreground. "
                f"Bright magenta-pink and sunshine yellow, pure summer energy.",
                f"Three women at an outdoor summer festival, laughing with hair flying in the warm breeze — "
                f"colourful festival lights behind them, {p} products on the picnic blanket. "
                f"Vibrant sunshine yellow and magenta palette, joyful summer sisterhood.",
            ])
        if _is_autumn:
            return (f"A woman walking through an autumn park doing a hair flip as golden and copper leaves swirl around her — "
                    f"amber afternoon light turning her shiny hair into a warm halo. {p} bottle on a wooden bench. "
                    f"Deep amber, rust and magenta palette, cosy autumn energy.")
        # Evergreen default — still pick from variants
        if any(x in p.lower() for x in ["serum", "oil", "scalp", "treat"]):
            return (f"Close-up slow-motion of a woman applying {p} drops onto her fingertips, "
                    f"running them through her hair as golden light particles trail behind. "
                    f"The {p} bottle gleams in warm studio light. Magenta-pink and sunshine yellow palette.")
        return _rnd.choice([
            f"A beautiful woman doing a slow-motion hair flip after washing with {p}, "
            f"her shiny hair cascading through golden light particles and warm bokeh. "
            f"The {p} bottle visible in foreground. Magenta-pink and sunshine yellow, dramatic rim lighting.",
            f"Two women (25-38) in a bright bathroom, one applying {p} as the other's hair transforms "
            f"into impossibly glossy flowing locks in slow motion. Warm studio light, brand palette.",
        ])

    def _rnorr_scene(p: str) -> str:
        if _is_christmas:
            return _rnd.choice([
                f"A multi-generational family of 5 (grandparents, parents, young child) gathered around "
                f"a beautifully set Christmas dinner table — the mother is serving the hero dish made with {p}, "
                f"faces glowing with joy. Decorated Christmas tree behind them, fairy lights strung overhead, "
                f"holly centrepiece, crackers and baubles on the table. {p} pack beside the serving bowl. "
                f"Deep forest green and gold palette, warm and genuinely festive.",
                f"A parent and two children (ages 5 and 8) cooking the Christmas feast together in a "
                f"festively decorated kitchen — the children standing on stools to help stir the pot with {p}. "
                f"Christmas cards on the mantle, fairy lights in the window, steam rising dramatically. "
                f"{p} box on the counter, deep green and red palette, real family magic.",
            ])
        if _is_diwali:
            return _rnd.choice([
                f"A South Asian family of 6 (multi-generational) gathered around a Diwali feast table — "
                f"diyas glowing everywhere, rangoli on the floor, the mother serving a dish made with {p} "
                f"to excited children. Jewel-toned fabrics, marigold garlands, warm golden diya light. "
                f"Deep green and vibrant gold palette, joyful and celebratory.",
                f"A grandmother and her adult daughter cooking together in a Diwali kitchen — "
                f"adding {p} to a rich bubbling pot, diyas reflected in the rising steam. "
                f"Traditional outfits, warm amber light, {p} pack on the counter beside fresh spices.",
            ])
        if _is_new_year:
            return _rnd.choice([
                f"A couple cooking a glamorous New Year's Eve dinner together — champagne flutes on the counter, "
                f"candles lit, midnight countdown on TV in the background. {p} being added dramatically to "
                f"a rich golden sauce, steam rising. Deep green and gold NYE palette, aspirational and warm.",
                f"Friends hosting a NYE dinner party — the host serving a beautifully plated dish made with {p}, "
                f"guests raising champagne flutes, city lights visible through the window. "
                f"Celebration energy, {p} pack on the kitchen island, sophisticated and joyful.",
            ])
        if _is_valentine:
            return (f"A couple cooking a romantic Valentine's dinner together by candlelight — "
                    f"red roses on the kitchen counter, {p} being stirred into a bubbling pot with a loving smile. "
                    f"Soft rose and candlelight warmth, {p} pack beside fresh herbs and rose petals. "
                    f"Intimate, romantic, deep green and rose-red palette.")
        if _is_easter:
            return (f"A family with young children cooking a bright Easter lunch together — "
                    f"decorated Easter eggs on the counter, spring flowers in a vase, pastel tablecloth. "
                    f"Parent and children stirring a pot with {p}, steam rising, natural spring light. "
                    f"Pastel and deep green palette, warm family togetherness.")
        if _is_halloween:
            return (f"A family carving pumpkins while making a cosy autumn stew with {p} — "
                    f"jack-o-lanterns glowing on the windowsill, autumn leaves outside. "
                    f"Warm amber and orange kitchen light, {p} box on the counter, comforting and festive.")
        if _is_summer:
            return (f"A family hosting an outdoor summer garden party — the hero cook serving "
                    f"a sizzling dish made with {p} at a table covered in fresh summer ingredients. "
                    f"Golden afternoon light, garden flowers, children running in the background. "
                    f"Bright and vibrant, {p} pack on the outdoor table, joyful summer energy.")
        if _is_autumn:
            return (f"A home cook making a rich autumn stew with {p} in a cosy kitchen — "
                    f"fallen leaves visible through the window, warm amber light, steaming pot. "
                    f"Warm earthy palette, {p} pack beside root vegetables, comfort and warmth.")
        # Evergreen default
        if any(x in p.lower() for x in ["gravy", "sauce", "cook-in", "liquid"]):
            return (f"A home cook pouring rich golden {p} over a sizzling pan of vegetables, "
                    f"dramatic steam and golden sauce trails in warm kitchen light. "
                    f"Deep forest green and yellow palette.")
        return _rnd.choice([
            f"A family of 4 cooking together — parent and children stirring a pot with {p}, "
            f"steam rising dramatically in warm amber kitchen light, {p} box on the counter. "
            f"Deep forest green and sunshine yellow, genuine family joy.",
            f"A home cook dropping {p} into a steaming pot, watching it dissolve into rich golden broth. "
            f"Steam rising dramatically, {p} box beside fresh vegetables. Deep green and yellow palette.",
        ])

    def _boozt_scene(p: str) -> str:
        if _is_christmas:
            return _rnd.choice([
                f"A group of 6 young people (20-30, mixed gender) at a Christmas house party — "
                f"Boozt cans raised high, laughing, tinsel draped everywhere, Christmas tree with coloured lights behind them. "
                f"Electric cobalt and Christmas red palette, cans PROMINENT and glistening, pure festive energy.",
                f"Friends celebrating on a rooftop terrace decorated for Christmas — city lights below, "
                f"fairy lights strung across the space, Boozt cans raised in a toast as soft snow drifts down. "
                f"Midnight navy and electric blue with Christmas gold, aspirational and electric.",
            ])
        if _is_new_year:
            return _rnd.choice([
                f"A crowd of young people celebrating New Year's Eve countdown — Boozt cans raised as "
                f"the clock strikes midnight, golden confetti exploding, fireworks visible through huge windows. "
                f"Electric cobalt blue and gold palette, unstoppable celebration energy, cans centre-frame.",
                f"Four friends on a penthouse rooftop at midnight — Boozt cans clinked together "
                f"as fireworks burst over the city skyline behind them, droplets flying in slow motion. "
                f"Deep navy and electric gold, pure NYE euphoria.",
            ])
        if _is_diwali:
            return (f"A group of young South Asian people (20-30) celebrating Diwali outdoors — "
                    f"Boozt cans raised in a toast surrounded by sparklers and diya lights, "
                    f"vibrant outfits, Diwali fireworks in the sky behind them. "
                    f"Electric cobalt and gold with warm Diwali colours, joyful and energetic.")
        if _is_valentine:
            return (f"A stylish couple sharing ice-cold Boozt cans on a Valentine's rooftop date — "
                    f"city lights and red heart bokeh in the background, condensation rolling down the cans. "
                    f"Rose-red and electric cobalt palette, intimate but energetic, cans centre-frame.")
        if _is_easter:
            return (f"Young people at a spring outdoor festival — Boozt cans in hand, "
                    f"pastel decorations and spring flowers everywhere, bright afternoon sun. "
                    f"Vibrant pastel and cobalt blue, fresh spring energy, cans prominent.")
        if _is_halloween:
            return (f"A Halloween party — young people in costumes raising Boozt cans, "
                    f"deep orange and purple strobe lighting, jack-o-lanterns glowing on the bar. "
                    f"Dark electric atmosphere, cobalt and amber/purple palette, pure Halloween energy.")
        if _is_summer:
            return _rnd.choice([
                f"A group of friends at a summer music festival raising Boozt cans to the sky — "
                f"stage lights behind them, golden hour sunlight, crowd energy. "
                f"Electric cobalt and sunshine, cans PROMINENT, euphoric summer festival atmosphere.",
                f"An athlete finishing an outdoor track session, cracking open a cold Boozt can — "
                f"condensation exploding in slow motion under brilliant summer sunlight. "
                f"Bright cobalt and white, performance energy, can centre-frame.",
            ])
        if _is_autumn:
            return (f"Young professionals at an autumn rooftop bar — Boozt cans in hand, "
                    f"copper and amber autumn leaves below, warm afternoon light. "
                    f"Deep navy and warm amber palette, stylish and energetic.")
        # Evergreen
        return _rnd.choice([
            f"A group of 5 young people (18-30, mixed gender) at an urban rooftop party — "
            f"Boozt cans raised high, electric blue lights, city skyline behind them. "
            f"Deep midnight navy and cobalt blue, pure charged celebration energy.",
            f"A confident athlete mid-sprint through a city street, Boozt can thrust toward the camera — "
            f"electric arcs and blue light trails, can PROMINENT and glistening. "
            f"Deep navy and electric cobalt, unstoppable momentum.",
        ])

    def _glenfiddich_scene(p: str) -> str:
        if _is_christmas:
            return _rnd.choice([
                f"Four sophisticated adults (30-55) around a beautifully set Christmas dinner table — "
                f"crystal whisky glasses raised in a toast, {p} bottle centre-stage, amber liquid catching "
                f"candlelight and fireplace glow. Holly and pine centrepiece, Christmas crackers, "
                f"tall taper candles. Deep teal and Christmas gold palette, understated luxury.",
                f"A {p} bottle wrapped in a velvet ribbon sitting as the hero Christmas gift on a "
                f"mantelpiece above a roaring fireplace — Christmas stockings hung, fairy lights reflected "
                f"in the bottle, fire casting warm amber light. Premium aspirational, the ultimate gift.",
            ])
        if _is_new_year:
            return _rnd.choice([
                f"Three sophisticated adults in black tie at a NYE gala — crystal Glenfiddich glasses "
                f"raised as midnight strikes, {p} bottle prominently lit, confetti beginning to fall. "
                f"Deep teal and gold palette, elegant and celebratory, refined NYE luxury.",
                f"An intimate couple's NYE toast — two {p} crystal glasses catching the light "
                f"as fireworks burst outside the floor-to-ceiling windows, the bottle on the table. "
                f"Deep navy, teal and gold, cinematic and aspirational.",
            ])
        if _is_valentine:
            return (f"A couple sharing a glass of {p} at an intimate candlelit Valentine's dinner — "
                    f"red roses on the table, {p} bottle between them catching the candlelight, "
                    f"both looking at each other with warmth. Deep teal and rose-red palette, "
                    f"sophisticated romantic elegance.")
        if _is_diwali:
            return (f"A sophisticated Diwali celebration gathering — {p} bottle on a beautifully set table "
                    f"with diyas and marigolds, adults raising crystal glasses in a toast. "
                    f"Rich jewel tones and gold, warm diya light, premium and festive.")
        if _is_summer:
            return (f"A sophisticated man in a linen blazer at a sunlit outdoor terrace bar, "
                    f"pouring {p} over ice into a crystal glass — golden afternoon light, "
                    f"ocean or countryside vista behind him. Teal and chartreuse, premium summer leisure.")
        if _is_halloween:
            return (f"A moody Halloween evening — a lone figure in an elegant dark outfit pours {p} "
                    f"in a dramatically lit study, jack-o-lanterns casting amber light, "
                    f"the bottle prominent on a mahogany desk. Deep teal and amber, gothic sophistication.")
        # Evergreen
        return _rnd.choice([
            f"A sophisticated man in a dark green blazer in a moody bar, picking up a glass of {p} "
            f"as amber liquid catches warm candlelight. Glenfiddich AMF1 bottle gleams in the foreground. "
            f"Cinematic dolly push-in, deep teal and chartreuse brand palette, restrained confidence.",
            f"Three adults at an intimate private dining table raising crystal Glenfiddich glasses — "
            f"{p} bottle centre-stage under warm pendant lighting. Deep teal and gold, premium occasion.",
        ])

    def _ubs_scene(_p: str) -> str:
        # Pure visual/lifestyle — ZERO brand name, financial, or wealth terms (RAI filter).
        if _is_christmas:
            return _rnd.choice([
                "A family of 4 (parents and two young children) walking hand-in-hand through a "
                "beautifully decorated Christmas market — stalls glowing with fairy lights, soft snow falling, "
                "warm golden light on their faces, red scarves and winter coats, children laughing with delight. "
                "Cinematic slow dolly, shallow depth of field, warm festive joy.",
                "A couple decorating their home for Christmas — hanging ornaments on the tree together, "
                "fairy lights twinkling, cosy living room with fireplace glowing. "
                "Intimate, warm, aspirational domestic happiness. Slow-motion close-ups of their smiling faces.",
            ])
        if _is_new_year:
            return _rnd.choice([
                "A family on a rooftop terrace watching fireworks at midnight — parents lifting children "
                "to see the colourful bursts over the city skyline, golden confetti falling around them. "
                "Wide cinematic shot, joy and optimism, warm amber and gold tones.",
                "A couple dressed elegantly embracing as midnight fireworks illuminate the sky behind them — "
                "confetti falling, city lights below, faces lit with golden light. "
                "Cinematic and aspirational, intimate but grand.",
            ])
        if _is_diwali:
            return _rnd.choice([
                "A family lighting diyas together on their home doorstep at dusk — "
                "three generations (grandparents, parents, children) in traditional festive attire, "
                "golden diya light warming their faces, rangoli patterns at their feet. "
                "Warm and joyful, cinematic slow-motion, rich jewel tones.",
                "A couple sharing a Diwali meal together by the warm glow of dozens of diyas — "
                "traditional outfits, flower garlands, soft Diwali fireworks visible through the window. "
                "Intimate and aspirational.",
            ])
        if _is_valentine:
            return _rnd.choice([
                "A couple walking through a rose-lit city street on Valentine's evening — "
                "boutique windows decorated with hearts and roses, warm pink bokeh, "
                "holding hands and smiling at each other. Cinematic and romantic.",
                "A couple at an intimate candlelit restaurant — roses on the table, "
                "soft warm lighting, genuine laughter and connection. "
                "Close-up of their hands together, shallow depth of field, rose and gold tones.",
            ])
        if _is_easter:
            return ("A young family on an Easter morning egg hunt in a sunny garden — "
                    "children in pastel outfits discovering Easter eggs among spring flowers, "
                    "parents watching and laughing. Fresh spring light, pastel palette, pure joy.")
        if _is_halloween:
            return ("A family carving pumpkins together on a cosy autumn evening — "
                    "jack-o-lanterns glowing on the porch, children in costumes laughing, "
                    "warm amber light. Wholesome family Halloween moment.")
        if _is_summer:
            return _rnd.choice([
                "A family on a sunny summer holiday — children running on the beach, "
                "parents laughing in golden hour light, carefree and joyful. "
                "Cinematic wide shot, warm and aspirational.",
                "A couple walking confidently through a sun-drenched European city square — "
                "golden afternoon light, vibrant summer energy, modern and at ease.",
            ])
        if _is_autumn:
            return ("A couple walking through a stunning autumn park — "
                    "copper and golden leaves falling around them, warm afternoon light, "
                    "cosy scarves, genuinely happy. Cinematic and aspirational.")
        if _is_winter:
            return ("A family in cosy winter outerwear walking through a frosted landscape — "
                    "breath visible in the crisp air, children playing in the snow, "
                    "warm smiles, aspirational winter lifestyle.")
        return _rnd.choice([
            "A couple walks confidently through a sunlit city street, smiling warmly, "
            "golden light falling across elegant architecture. "
            "Slow cinematic dolly, shallow depth of field, clean and aspirational.",
            "A family of 4 walking together through a beautiful park on a bright morning — "
            "children running ahead, parents hand-in-hand, warm natural light. "
            "Cinematic and uplifting, clean and modern.",
        ])

    _BRAND_SCENE_FN = {
        "Sunglow":     _sunglow_scene,
        "Rnorr":       _rnorr_scene,
        "Boozt":       _boozt_scene,
        "Glenfiddich": _glenfiddich_scene,
        "UBS Bank":    _ubs_scene,
    }
    brand_scene = (
        _BRAND_SCENE_FN[brand](_prod) if brand in _BRAND_SCENE_FN
        else f"A premium cinematic advertising scene for {brand}, photorealistic, elegant and aspirational."
    )

    # ── Step 3: Generate the rich 80-100 word cinematic prompt (same as full pipeline) ──
    _voiceover_line = f'A warm confident voiceover says: "{voiceover}"' if voiceover \
        else "A warm confident voiceover narrates the campaign tagline."
    prompt_req = (
        f"Write a single cinematic video+audio generation prompt (80-100 words) "
        f"for a 6-second {brand} campaign reel with voiceover.\n\n"
        f"Brand: {brand}\n"
        f"Product: {product or '(service brand — no physical product)'}\n"
        f"Campaign Big Idea: {big_idea}\n"
        f"Season/Context: {season or 'evergreen'}\n"
        f"Audience: {audience}\n"
        f"Voiceover text: \"{voiceover}\"\n"
        f"Base visual direction: {brand_scene}\n\n"
        f"Rules:\n"
        f"- Photorealistic, premium advertising quality, dynamic motion, brand colours prominent\n"
        f"- AUDIO: upbeat brand-appropriate background music + {_voiceover_line}\n"
        f"- The voiceover should be delivered confidently and warmly over the music\n"
        f"- No text or typography visible in the image\n"
        f"- CRITICAL: Do NOT use any financial or wealth terms: no 'wealth', 'investment', "
        f"'high-net-worth', 'banking', 'financial', 'portfolio', 'returns', 'assets', 'affluent', "
        f"'prosperity'. Describe only pure visual/lifestyle/emotional content.\n"
        f"Output the prompt only — no labels, no markdown, no explanation."
    )
    try:
        resp = _genai_client().models.generate_content(
            model=settings.gemini_model_reasoning,
            contents=prompt_req,
        )
        raw = (resp.text or "").strip()
        import re as _re
        # Strip any markdown label Gemini might prepend (e.g. "**VIDEO:**", "**Prompt:**")
        raw = _re.sub(r"^\*{0,2}[A-Z][A-Z\s:]{1,20}\*{0,2}:?\s*", "", raw).strip()
        # Also strip financial/wealth terms that slip through — replace with neutral alternatives
        # Only strip terms that historically triggered Veo RAI code 15236754.
        # "financial" is NOT in this list — "a clear financial future" is a
        # legitimate lifestyle phrase and safe for Veo.
        _financial_terms = [
            (r"\bhigh[\s-]net[\s-]worth\b", "discerning"),
            (r"\bwealth management\b", "lifestyle planning"),
            (r"\baffluent\b",           "accomplished"),
            (r"\bprosperous\b",         "fulfilled"),
            (r"\bstock market\b",       "opportunity"),
            (r"\bportfolio\b",          "journey"),
        ]
        for pattern, replacement in _financial_terms:
            raw = _re.sub(pattern, replacement, raw, flags=_re.IGNORECASE)
        final_prompt = raw
        if not final_prompt:
            final_prompt = f"Cinematic 6-second lifestyle reel. {brand_scene} AUDIO: {_voiceover_line}. No text."
    except Exception as e:
        logger.warning("standalone_reel_prompt_gen_failed", error=str(e))
        final_prompt = f"Cinematic 6-second {brand} campaign reel. {brand_scene} AUDIO: {_voiceover_line}. Photorealistic, premium quality. No text."

    logger.info("standalone_reel_prompt_ready", prompt=final_prompt[:120])

    # ── Step 4: Pure text-to-video Veo call (same as full pipeline — no image params) ──
    video_b64 = ""
    try:
        import base64
        import time as _time
        from google.genai.types import GenerateVideosConfig

        veo_model = os.getenv("VEO_MODEL", "veo-3.1-generate-001")
        client    = _genai_client()
        page_id   = uuid.uuid4().hex[:12]
        out_uri   = f"gs://{settings.gcs_bucket}/outputs/standalone-{page_id}/reel.mp4"

        _neg_prompt = (
            "text, words, subtitles, financial charts, graphs, stock prices, "
            "news tickers, legal disclaimers, violence, explicit content"
        )

        # Pure text-to-video — no last_frame/image params.
        # last_frame is only supported in image-to-video mode; passing it in
        # text-to-video always returns an empty result and triggers a wasted retry.
        def _veo_call(video_text: str) -> object:
            page = uuid.uuid4().hex[:12]
            uri  = f"gs://{settings.gcs_bucket}/outputs/standalone-{page}/reel.mp4"
            return client.models.generate_videos(
                model  = veo_model,
                prompt = video_text,
                config = GenerateVideosConfig(
                    aspect_ratio="16:9", duration_seconds=6,
                    output_gcs_uri=uri, number_of_videos=1, generate_audio=True,
                    negative_prompt=_neg_prompt,
                ),
            )

        def _poll(operation) -> object:
            deadline = _time.time() + 480
            while not operation.done:
                if _time.time() > deadline:
                    raise TimeoutError("Veo generation timed out after 8 minutes")
                _time.sleep(20)
                operation = client.operations.get(operation)
            return operation

        def _has_video(op) -> bool:
            return bool(op.result and op.result.generated_videos)

        def _rai_reasons(op) -> list:
            return getattr(op.result, "rai_media_filtered_reasons", None) if op and op.result else None

        operation = _poll(_veo_call(final_prompt))

        # If prompt was RAI-blocked, retry with the minimal safe scene-only fallback
        _rai = _rai_reasons(operation)
        if _rai and not _has_video(operation):
            logger.warning("standalone_reel_rai_blocked_retrying", model=veo_model, reasons=_rai)
            _safe_prompt = (
                # Safe fallback: pure lifestyle scene, no brand name, no financial terms
                f"Cinematic 6-second lifestyle advertisement. {brand_scene} "
                f"Photorealistic, premium quality, smooth camera motion, warm and aspirational mood. "
                f"AUDIO: gentle upbeat music with a confident voiceover. No text visible."
            )
            operation = _poll(_veo_call(_safe_prompt, with_end=False))

        if operation.result and operation.result.generated_videos:
            video_gcs = operation.result.generated_videos[0].video.uri
            from google.cloud import storage as _gcs
            without = video_gcs[5:]
            bucket_name, _, blob_path = without.partition("/")
            video_bytes = _gcs.Client().bucket(bucket_name).blob(blob_path).download_as_bytes()
            # Burn headline as an end-card (start_sec=4.5 so text appears
            # AFTER the voiceover audio finishes, not simultaneously).
            # Also apply the same financial-term cleanup used on the Veo
            # prompt so the on-screen text matches what the audio says.
            try:
                # Use the original voiceover as the burned text — "financial future"
                # is a valid campaign line and should appear on screen as-is.
                # Financial-term substitution only lives in the Veo video PROMPT
                # (to avoid RAI blocks on the generated scene), not in the overlay.
                _burn_text = voiceover
                # Single FFmpeg pass: text lower-third + logo end-card together.
                # Two separate passes caused the second pass to silently drop
                # everything from the first pass on Windows.
                import shutil as _sh, subprocess as _sp, tempfile as _tf
                from pathlib import Path as _PP
                from io import BytesIO as _BIO

                if _sh.which("ffmpeg"):
                    # ── Font ──────────────────────────────────────────────
                    from app.brand_assets import get_asset_loader as _gal
                    _fdir = _PP(__file__).resolve().parent.parent / "bucket" / "brands" / brand / "Font"
                    _ttf  = None
                    if _fdir.is_dir():
                        _ttf = next((str(f) for f in sorted(_fdir.glob("*.ttf"))
                                     if "italic" not in f.name.lower() and "bold" not in f.name.lower()), None) \
                            or next((str(f) for f in sorted(_fdir.glob("*.ttf"))), None)
                    # Windows system font fallback — ensures text always renders
                    if not _ttf:
                        import os as _os
                        for _wf in [
                            r"C:\Windows\Fonts\arial.ttf",
                            r"C:\Windows\Fonts\calibri.ttf",
                            r"C:\Windows\Fonts\segoeui.ttf",
                        ]:
                            if _os.path.exists(_wf):
                                _ttf = _wf
                                break
                    logger.debug("standalone_reel_font", brand=brand, ttf=str(_ttf))

                    # ── Raw logo PNG (no background card) ────────────────
                    _logo_raw = None
                    _logo_w   = 200   # target width; height scales proportionally
                    try:
                        from app.creative_pipeline import _load_bytes as _lb
                        _ldr   = _gal()
                        _logos = _ldr.list_logos(brand)
                        if _logos:
                            _bslug = brand.split()[0].lower()
                            def _pick(_ps):
                                return (
                                    next((p for p in _ps if _bslug in p.lower() and "_dark" in p.lower()), None) or
                                    next((p for p in _ps if _bslug in p.lower()
                                          and not any(k in p.lower() for k in ("_white","_green","_red","_blue","_yellow"))), None) or
                                    next((p for p in _ps if _bslug in p.lower()), None) or
                                    _ps[0]
                                )
                            _logo_raw = _lb(_pick(_logos))
                    except Exception:
                        pass

                    with _tf.TemporaryDirectory() as _td:
                        _vin  = _PP(_td) / "input.mp4"
                        _vout = _PP(_td) / "output.mp4"
                        _vin.write_bytes(video_bytes)

                        # Copy font to temp dir (avoids Windows path/colon issues)
                        _font_arg = None
                        if _ttf:
                            _ft = _PP(_td) / "font.ttf"
                            _ft.write_bytes(_PP(_ttf).read_bytes())
                            _font_arg = "font.ttf"

                        _has_logo = _logo_raw is not None
                        if _has_logo:
                            _lc_path = _PP(_td) / "logo.png"
                            _lc_path.write_bytes(_logo_raw)

                        # Build combined filter_complex ─────────────────────
                        def _esc_s(s):
                            return s.replace("\\","\\\\").replace("'","\\'").replace(":","\\:")

                        def _wrap_s(text, max_chars=40):
                            text = text.strip()
                            if len(text) <= max_chars:
                                return text, ""
                            idx = text.rfind(" ", 0, max_chars)
                            if idx == -1: idx = max_chars
                            return text[:idx].strip(), text[idx:].strip()

                        if _font_arg and _burn_text.strip():
                            _l1, _l2 = _wrap_s(_burn_text[:80])
                            _hl1 = _esc_s(_l1)
                            _two = bool(_l2)
                            _y1  = "H-145" if _two else "H-100"
                            _y2  = "H-100"
                            _txt_f = (
                                f"drawtext=fontfile={_font_arg}:text='{_hl1}':"
                                f"fontsize=36:fontcolor=white:x=60:y={_y1}:"
                                f"enable=between(t\\,1.5\\,6):"
                                f"alpha=if(lt(t\\,2.0)\\,(t-1.5)/0.5\\,1):"
                                f"box=1:boxcolor=black@0.55:boxborderw=16"
                            )
                            if _two:
                                _hl2 = _esc_s(_l2[:80])
                                _txt_f += (
                                    f",drawtext=fontfile={_font_arg}:text='{_hl2}':"
                                    f"fontsize=36:fontcolor=white:x=60:y={_y2}:"
                                    f"enable=between(t\\,1.5\\,6):"
                                    f"alpha=if(lt(t\\,2.0)\\,(t-1.5)/0.5\\,1):"
                                    f"box=1:boxcolor=black@0.55:boxborderw=16"
                                )
                        else:
                            _txt_f = None

                        # format=auto lets FFmpeg use the PNG alpha — no background card needed
                        if _has_logo and _txt_f:
                            _fc = (
                                f"[0:v]{_txt_f}[txt];"
                                f"[1:v]scale={_logo_w}:-1[logo];"
                                f"[txt][logo]overlay=W-w-24:24:format=auto:"
                                f"enable=between(t\\,4.2\\,6)[vout]"
                            )
                            _cmd = ["ffmpeg","-y","-i","input.mp4","-i","logo.png",
                                    "-filter_complex",_fc,
                                    "-map","[vout]","-map","0:a?",
                                    "-c:v","libx264","-preset","fast","-crf","20",
                                    "-c:a","copy","output.mp4"]
                        elif _has_logo:
                            _fc = (
                                f"[1:v]scale={_logo_w}:-1[logo];"
                                f"[0:v][logo]overlay=W-w-24:24:format=auto:"
                                f"enable=between(t\\,4.2\\,6)[vout]"
                            )
                            _cmd = ["ffmpeg","-y","-i","input.mp4","-i","logo.png",
                                    "-filter_complex",_fc,
                                    "-map","[vout]","-map","0:a?",
                                    "-c:v","libx264","-preset","fast","-crf","20",
                                    "-c:a","copy","output.mp4"]
                        elif _txt_f:
                            _cmd = ["ffmpeg","-y","-i","input.mp4",
                                    "-vf",_txt_f,
                                    "-c:v","libx264","-preset","fast","-crf","20",
                                    "-c:a","copy","output.mp4"]
                        else:
                            _cmd = None

                        if _cmd:
                            _r = _sp.run(_cmd, capture_output=True, timeout=120, cwd=_td)
                            if _r.returncode == 0 and _vout.exists():
                                video_bytes = _vout.read_bytes()
                                logger.info("standalone_reel_overlay_applied", brand=brand)
                            else:
                                logger.warning("standalone_reel_overlay_failed", brand=brand,
                                               stderr=_r.stderr.decode(errors="ignore")[-400:])
            except Exception as _ov_err:
                logger.warning("standalone_reel_overlay_error", brand=brand, error=str(_ov_err))
            video_b64 = base64.b64encode(video_bytes).decode("utf-8")
            logger.info("standalone_reel_succeeded", model=veo_model)
        else:
            _rai2 = getattr(operation.result, "rai_media_filtered_reasons", None) if operation and operation.result else None
            logger.warning("standalone_reel_empty", model=veo_model, rai=_rai2)
    except Exception as e:
        logger.warning("standalone_reel_failed", brand=brand, error=str(e))

    return {"agent": "reel", "brand": brand, "headline": voiceover, "video_b64": video_b64}


_RUNNERS = {
    "briefing": run_briefing,
    "strategy": run_strategy,
    "copy":     run_copy,
    "culture":  run_culture,
    "channel":  run_channel,
    "kv":       run_kv,
    "reel":     run_reel,
}


def run_agent_standalone(agent_key: str, text: str) -> dict:
    """text is the whole free-text prompt, e.g. "UBS Bank for UK market, festive: christmas" —
    the brand is detected from it automatically rather than passed separately."""
    runner = _RUNNERS.get(agent_key)
    if not runner:
        raise ValueError(f"No standalone runner for agent '{agent_key}'.")
    brand = _extract_brand(text)
    if not brand:
        raise ValueError(
            "Couldn't tell which brand this is for — mention an uploaded brand's name in your prompt "
            '(e.g. "UBS Bank for UK market, festive: christmas").'
        )
    logger.info("agent_standalone_run", agent=agent_key, brand=brand)
    return runner(brand, text)
